language: node_js
node_js:
  - '6'
cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - npm run lint
  - npm run build
  - npm test

before_deploy: npm install -g firebase-tools

deploy:
  provider: script
  script: cd packages/imtry-assistant/ && firebase --project imtry-9bd92 --token $FIREBASE_TOKEN deploy --only functions:dialogflowFirebaseFulfillment
  skip_cleanup: true
  on:
    branch: master
